const MONTH={jan:'january',january:'january',feb:'february',february:'february',mar:'march',march:'march',apr:'april',april:'april',may:'may',jun:'june',june:'june',jul:'july',july:'july',aug:'august',august:'august',sep:'september',sept:'september',september:'september',oct:'october',october:'october',nov:'november',november:'november',dec:'december',december:'december'};
const MONTH_RE=Object.keys(MONTH).sort((a,b)=>b.length-a.length).join('|');
const COUNTRY={putin:'russia',zelensky:'ukraine',xi:'china',macron:'france',netanyahu:'israel'};
const FILLER=new Set('what are is the of on by to for a an in and or if will would could being be polymarket odds probability chance chances market markets yes no price trading outcome outcomes'.split(' '));
const WEAK=new Set('out president prime minister before after during removed leave leaves office win wins lose loses happen happens perform by end'.split(' '));
function isPolymarketOddsQuestion(q){return /\bpolymarket\b/i.test(q)&&/\b(odds|probability|chance|chances|price|market|yes|no)\b/i.test(q)}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function slugify(s){return norm(s).replace(/\s+/g,'-')}
function textOf(m){return norm(m?.question||m?.title||m?.slug||m?.market_slug||'')}
function datePart(q){const m=String(q||'').toLowerCase().match(new RegExp('\\b('+MONTH_RE+')\\b\\s*([1-3]?\\d)(?:st|nd|rd|th)?'));return m?{month:MONTH[m[1]]||m[1],short:(MONTH[m[1]]||m[1]).slice(0,3),day:String(Number(m[2]))}:null}
function keyTerms(q){const d=datePart(q),out=[];for(const w of norm(q).split(/\s+/)){if(!w||FILLER.has(w))continue;if(MONTH[w]){out.push(MONTH[w].slice(0,3));continue}if(/^\d+$/.test(w)){if(d&&w===d.day)out.push(w);continue}out.push(w)}return[...new Set(out)]}
function subjectTerms(q){return keyTerms(q).filter(w=>!WEAK.has(w)&&!MONTH[w]&&!/^\d+$/.test(w)).slice(0,4)}
function hasSubj(t,subs){return !subs.length||subs.some(s=>t.includes(s))}
function hasDate(t,d){return !d||(t.includes(d.short)&&t.includes(d.day))}
function decode(v){if(Array.isArray(v))return v;if(typeof v!=='string')return[];try{let p=JSON.parse(v);return Array.isArray(p)?p:[]}catch{return[]}}
function outcomes(m){let names=decode(m.outcomes||m.outcomeNames),prices=decode(m.outcomePrices).map(Number);return names.map((n,i)=>({name:String(n||'').trim(),price:Number.isFinite(prices[i])?prices[i]:null}))}
function pick(m,want='Yes'){let o=outcomes(m),w=String(want||'Yes').toLowerCase();return o.find(x=>x.name.toLowerCase()===w)||o.find(x=>x.name.toLowerCase().includes(w))||o.find(x=>x.name.toLowerCase()==='yes')||o[0]||{name:want,price:null}}
function fmt(p){if(p==null||!Number.isFinite(Number(p)))return'?';let pct=Number(p)*100;if(pct===0)return'<0.1%';return pct>0&&pct<1?pct.toFixed(2)+'%':pct.toFixed(1)+'%'}
async function get(url){try{let r=await fetch(url,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(10000)});return r.ok?await r.json():null}catch{return null}}
function marketsFrom(data){if(!data)return[];let roots=Array.isArray(data)?data:Array.isArray(data.data)?data.data:Array.isArray(data.events)?data.events:[data],out=[];for(const r of roots){if(!r)continue;if(Array.isArray(r.markets))out.push(...r.markets);else if(r.outcomePrices&&(r.question||r.title))out.push(r);else if(r.slug&&r.ticker)out.push(r)}return out.filter(m=>m&&(m.question||m.title)&&m.outcomePrices)}
async function groq(prompt,fb){let key=process.env.GROQ_API_KEY;if(!key)return fb;try{let r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},signal:AbortSignal.timeout(9000),body:JSON.stringify({model:'llama-3.1-8b-instant',temperature:0,max_tokens:500,messages:[{role:'user',content:prompt}]})});if(!r.ok)return fb;let raw=((await r.json()).choices?.[0]?.message?.content||'').replace(/```json|```/g,'').trim();let m=raw.match(/\{[\s\S]*\}/);return JSON.parse(m?m[0]:raw)}catch{return fb}}
function urlSlugs(q){let m=String(q||'').match(/polymarket\.com\/event\/([^\s?#]+)(?:\/([^\s?#]+))?/i);return m?[m[2],m[1]].filter(Boolean).map(x=>x.replace(/#.*$/,'')):[]}
function deterministicSlugs(q,parsed){let out=urlSlugs(q),d=datePart(q),subs=(parsed.subjects?.length?parsed.subjects:subjectTerms(q)).map(slugify).filter(Boolean),sub=subs[0];if(!d||!sub)return[...new Set(out)];let s=String(q).toLowerCase(),country=(s.match(/president\s+of\s+([a-z]+)/)||[])[1]||COUNTRY[sub]||'',date=`${d.month}-${d.day}`;if(/\bout\b/.test(s)){if(/president/.test(s)||country){if(country)out.push(`${sub}-out-as-president-of-${slugify(country)}-by-${date}`);out.push(`${sub}-out-as-president-by-${date}`);if(country)out.push(`${sub}-out-as-president-of-${slugify(country)}-before-2027`)}out.push(`${sub}-out-by-${date}`);out.push(`${sub}-out-before-2027`)}out.push(`${subs.join('-')}-by-${date}`);return[...new Set(out)]}
async function parse(q){let subs=subjectTerms(q),d=datePart(q),fb={subjects:subs,dateTerms:d?[d.short,d.day]:[],outcome:'Yes',searchQueries:[keyTerms(q).join(' '),subs.join(' '),subs.concat(['out']).join(' ')].filter(Boolean),slugCandidates:[]};let p=await groq('Parse Polymarket odds question as JSON: {"subjects":[main entities/topics],"dateTerms":[month/day],"outcome":"Yes/No/exact outcome","searchQueries":[queries],"slugCandidates":[event slugs]}. Question: '+q,fb);p.subjects=Array.isArray(p.subjects)&&p.subjects.length?p.subjects.map(x=>String(x).toLowerCase()):fb.subjects;p.dateTerms=Array.isArray(p.dateTerms)?[...new Set([...p.dateTerms.map(x=>String(x).toLowerCase().slice(0,3)),...fb.dateTerms])]:fb.dateTerms;p.outcome=p.outcome||'Yes';p.searchQueries=Array.isArray(p.searchQueries)&&p.searchQueries.length?p.searchQueries:fb.searchQueries;p.slugCandidates=[...new Set([...deterministicSlugs(q,p),...(Array.isArray(p.slugCandidates)?p.slugCandidates:[])].filter(Boolean))];return p}
function bestMarket(ms,slug){let s=slugify(slug);return ms.find(m=>slugify(m.slug||m.market_slug||'')===s)||ms.find(m=>slugify(m.slug||m.market_slug||'').includes(s))||ms.find(m=>s.includes(slugify(m.slug||m.market_slug||'')))||ms[0]}
async function exact(slug){let page='https://polymarket.com/event/'+slug;for(const u of[`https://gamma-api.polymarket.com/events/slug/${encodeURIComponent(slug)}`,`https://gamma-api.polymarket.com/events?slug=${encodeURIComponent(slug)}`,`https://gamma-api.polymarket.com/markets?slug=${encodeURIComponent(slug)}`]){let ms=marketsFrom(await get(u));if(ms.length)return{market:bestMarket(ms,slug),url:page,all:ms}}return null}
async function search(qs){let by=new Map();for(const q of[...new Set((qs||[]).filter(Boolean))]){for(const u of['https://gamma-api.polymarket.com/events?limit=50&search='+encodeURIComponent(q),'https://gamma-api.polymarket.com/markets?active=true&closed=false&limit=50&search='+encodeURIComponent(q),'https://gamma-api.polymarket.com/markets?limit=50&search='+encodeURIComponent(q)]){for(const m of marketsFrom(await get(u)))by.set(m.id||m.slug||m.market_slug||m.question,m)}}return[...by.values()]}
function score(q,m){let t=textOf(m),terms=keyTerms(q),subs=subjectTerms(q),d=datePart(q);if(!hasSubj(t,subs))return-999;if(!hasDate(t,d))return-999;let sc=0;for(const term of terms)if(t.includes(term))sc+=WEAK.has(term)?1:3;if(d)sc+=8;if(subs.length)sc+=10;return sc}
async function aiPick(q,ms){if(ms.length<=1)return{index:ms.length?0:-1,outcome:'Yes'};let list=ms.slice(0,12).map((m,i)=>`${i}: ${m.question||m.title||m.slug}`).join('\n');return await groq('Pick the exact Polymarket market. Return {"index":number,"outcome":"Yes/No/exact outcome"}; index -1 if none match subject/topic/date. Question: '+q+'\nMarkets:\n'+list,{index:0,outcome:'Yes'})}
function ans(m,outcome,urlOverride){let title=m.question||m.title||m.slug||'Selected market',o=pick(m,outcome),slug=m.slug||m.market_slug||'',url=urlOverride||(slug?'https://polymarket.com/event/'+slug:'https://polymarket.com');return{ok:true,kind:'polymarket',answer:`${o.name||'Outcome'} is trading at ${fmt(o.price)} on Polymarket for: ${title}`,sources:[{domain:'polymarket',title:title.slice(0,90),url}],headlines:[]}}
async function answerPolymarketOddsQuestion(q){let p=await parse(q);for(const slug of p.slugCandidates){let ex=await exact(slug);if(ex?.market&&score(q,ex.market)>0)return ans(ex.market,p.outcome,ex.url)}let candidates=(await search(p.searchQueries)).map(m=>({m,s:score(q,m)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).map(x=>x.m);if(!candidates.length)return{ok:false,kind:'polymarket',answer:'I could not find a Polymarket market that matches the subject/topic/date in your question.',sources:[],headlines:[]};let picked=await aiPick(q,candidates);if(Number(picked.index)<0||Number(picked.index)>=Math.min(12,candidates.length))return{ok:false,kind:'polymarket',answer:'I found Polymarket results, but none clearly matched your question.',sources:[],headlines:[]};return ans(candidates[Number(picked.index)],picked.outcome||p.outcome)}
module.exports={isPolymarketOddsQuestion,answerPolymarketOddsQuestion};