const MONTH={jan:'january',january:'january',feb:'february',february:'february',mar:'march',march:'march',apr:'april',april:'april',may:'may',jun:'june',june:'june',jul:'july',july:'july',aug:'august',august:'august',sep:'september',sept:'september',september:'september',oct:'october',october:'october',nov:'november',november:'november',dec:'december',december:'december'};
const MONTH_RE=Object.keys(MONTH).sort((a,b)=>b.length-a.length).join('|');
const COUNTRY={putin:'russia',zelensky:'ukraine',xi:'china',macron:'france',netanyahu:'israel'};
const FILLER=new Set('what are is the of on by to for a an in and or if will would could being be polymarket odds probability chance chances market markets yes no price trading outcome outcomes'.split(' '));
const WEAK=new Set('out president prime minister before after during removed leave leaves office win wins lose loses happen happens perform by end'.split(' '));
function isPolymarketOddsQuestion(q){return /\bpolymarket\b/i.test(q)&&/\b(odds|probability|chance|chances|price|market|yes|no)\b/i.test(q)}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function slugify(s){return norm(s).replace(/\s+/g,'-')}
function textOf(m){return norm(m?.question||m?.title||m?.slug||m?.market_slug||'')}
function datePart(q){let m=String(q||'').toLowerCase().match(new RegExp('\\b('+MONTH_RE+')\\b\\s*([1-3]?\\d)(?:st|nd|rd|th)?'));return m?{month:MONTH[m[1]]||m[1],short:(MONTH[m[1]]||m[1]).slice(0,3),day:String(Number(m[2]))}:null}
function keyTerms(q){let d=datePart(q),out=[];for(let w of norm(q).split(/\s+/)){if(!w||FILLER.has(w))continue;if(MONTH[w]){out.push(MONTH[w].slice(0,3));continue}if(/^\d+$/.test(w)){if(d&&w===d.day)out.push(w);continue}out.push(w)}return[...new Set(out)]}
function subjects(q){return keyTerms(q).filter(w=>!WEAK.has(w)&&!MONTH[w]&&!/^\d+$/.test(w)).slice(0,4)}
function decode(v){if(Array.isArray(v))return v;if(typeof v!=='string')return[];try{let p=JSON.parse(v);return Array.isArray(p)?p:[]}catch{return[]}}
function outcomes(m){let names=decode(m.outcomes||m.outcomeNames),prices=decode(m.outcomePrices).map(Number);return names.map((n,i)=>({name:String(n||'').trim(),price:Number.isFinite(prices[i])?prices[i]:null}))}
function pick(m,w='Yes'){let outs=outcomes(m),want=String(w||'Yes').toLowerCase();return outs.find(o=>o.name.toLowerCase()===want)||outs.find(o=>o.name.toLowerCase().includes(want))||outs.find(o=>o.name.toLowerCase()==='yes')||outs[0]||{name:w,price:null}}
function fmt(p){if(p==null||!Number.isFinite(Number(p)))return'?';let pct=Number(p)*100;if(pct===0)return'<0.1%';return pct>0&&pct<1?pct.toFixed(2)+'%':pct.toFixed(1)+'%'}
async function j(url){try{let r=await fetch(url,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(10000)});return r.ok?await r.json():null}catch{return null}}
function marketsFrom(data){if(!data)return[];let roots=Array.isArray(data)?data:Array.isArray(data.data)?data.data:Array.isArray(data.events)?data.events:[data],out=[];for(let r of roots){if(!r)continue;if(Array.isArray(r.markets))out.push(...r.markets);else if(r.outcomePrices&&(r.question||r.title))out.push(r)}return out.filter(m=>m&&(m.question||m.title)&&m.outcomePrices)}
function score(q,m){let t=textOf(m),ks=keyTerms(q),subs=subjects(q),d=datePart(q);if(subs.length&&!subs.some(s=>t.includes(s)))return-999;if(d&&!(t.includes(d.short)&&t.includes(d.day)))return-999;let sc=0;for(let k of ks)if(t.includes(k))sc+=WEAK.has(k)?1:3;if(d)sc+=8;if(subs.length)sc+=10;return sc}
function urlSlugs(q){let m=String(q||'').match(/polymarket\.com\/event\/([^\s?#]+)(?:\/([^\s?#]+))?/i);return m?[m[2],m[1]].filter(Boolean).map(x=>x.replace(/#.*$/,'')):[]}
function deterministic(q){let out=urlSlugs(q),d=datePart(q),subs=subjects(q).map(slugify).filter(Boolean),sub=subs[0];if(!d||!sub)return[...new Set(out)];let s=String(q).toLowerCase(),country=(s.match(/president\s+of\s+([a-z]+)/)||[])[1]||COUNTRY[sub]||'',date=`${d.month}-${d.day}`;if(/\bout\b/.test(s)){if(/president/.test(s)||country){if(country)out.push(`${sub}-out-as-president-of-${slugify(country)}-by-${date}`);out.push(`${sub}-out-as-president-by-${date}`);if(country)out.push(`${sub}-out-as-president-of-${slugify(country)}-before-2027`)}out.push(`${sub}-out-by-${date}`);out.push(`${sub}-out-before-2027`)}out.push(`${subs.join('-')}-by-${date}`);return[...new Set(out)]}
async function exact(slug,q){let page='https://polymarket.com/event/'+slug;let all=[];for(let u of[`https://gamma-api.polymarket.com/events/slug/${encodeURIComponent(slug)}`,`https://gamma-api.polymarket.com/events?slug=${encodeURIComponent(slug)}`,`https://gamma-api.polymarket.com/markets?slug=${encodeURIComponent(slug)}`])all.push(...marketsFrom(await j(u)));if(!all.length)return null;let ranked=all.map(m=>({m,s:score(q,m),slugScore:slugify(m.slug||m.market_slug||'').includes(slugify(slug))?50:0})).filter(x=>x.s>0||x.slugScore>0).sort((a,b)=>(b.s+b.slugScore)-(a.s+a.slugScore));return ranked.length?{market:ranked[0].m,url:page}:null}
async function search(qs){let by=new Map();for(let q of[...new Set((qs||[]).filter(Boolean))])for(let u of['https://gamma-api.polymarket.com/events?limit=50&search='+encodeURIComponent(q),'https://gamma-api.polymarket.com/markets?active=true&closed=false&limit=50&search='+encodeURIComponent(q),'https://gamma-api.polymarket.com/markets?limit=50&search='+encodeURIComponent(q)])for(let m of marketsFrom(await j(u)))by.set(m.id||m.slug||m.market_slug||m.question,m);return[...by.values()]}
async function groq(prompt,fb){let key=process.env.GROQ_API_KEY;if(!key)return fb;try{let r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},signal:AbortSignal.timeout(9000),body:JSON.stringify({model:'llama-3.1-8b-instant',temperature:0,max_tokens:300,messages:[{role:'user',content:prompt}]})});if(!r.ok)return fb;let raw=((await r.json()).choices?.[0]?.message?.content||'').replace(/```json|```/g,'').trim(),m=raw.match(/\{[\s\S]*\}/);return JSON.parse(m?m[0]:raw)}catch{return fb}}
async function parse(q){let ks=keyTerms(q),subs=subjects(q),d=datePart(q),fb={searchQueries:[ks.join(' '),subs.join(' '),subs.concat(['out']).join(' ')].filter(Boolean),outcome:'Yes',slugCandidates:deterministic(q)};let p=await groq('Parse Polymarket odds question as JSON only: {"searchQueries":[queries],"outcome":"Yes/No/exact outcome","slugCandidates":[event slugs]}. Question: '+q,fb);p.searchQueries=Array.isArray(p.searchQueries)&&p.searchQueries.length?p.searchQueries:fb.searchQueries;p.outcome=p.outcome||'Yes';p.slugCandidates=[...new Set([...(Array.isArray(p.slugCandidates)?p.slugCandidates:[]),...fb.slugCandidates].filter(Boolean))];return p}
async function aiPick(q,ms){if(ms.length<=1)return{index:ms.length?0:-1,outcome:'Yes'};let list=ms.slice(0,12).map((m,i)=>`${i}: ${m.question||m.title||m.slug}`).join('\n');return await groq('Pick exact Polymarket market. Return {"index":number,"outcome":"Yes/No/exact outcome"}; index -1 if none match. Question: '+q+'\nMarkets:\n'+list,{index:0,outcome:'Yes'})}
function ans(m,outcome,urlOverride){let title=m.question||m.title||m.slug||'Selected market',o=pick(m,outcome),slug=m.slug||m.market_slug||'',url=urlOverride||(slug?'https://polymarket.com/event/'+slug:'https://polymarket.com');return{ok:true,kind:'polymarket',answer:`${o.name||'Outcome'} is trading at ${fmt(o.price)} on Polymarket for: ${title}`,sources:[{domain:'polymarket',title:title.slice(0,90),url}],headlines:[]}}
async function answerPolymarketOddsQuestion(q){let p=await parse(q);for(let slug of p.slugCandidates){let ex=await exact(slug,q);if(ex?.market)return ans(ex.market,p.outcome,ex.url)}let candidates=(await search(p.searchQueries)).map(m=>({m,s:score(q,m)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).map(x=>x.m);if(!candidates.length)return{ok:false,kind:'polymarket',answer:'I could not find a Polymarket market that matches the subject/topic/date in your question.',sources:[],headlines:[]};let picked=await aiPick(q,candidates);if(Number(picked.index)<0||Number(picked.index)>=Math.min(12,candidates.length))return{ok:false,kind:'polymarket',answer:'I found Polymarket results, but none clearly matched your question.',sources:[],headlines:[]};return ans(candidates[Number(picked.index)],picked.outcome||p.outcome)}
module.exports={isPolymarketOddsQuestion,answerPolymarketOddsQuestion};