const MONTH = {jan:'january',january:'january',feb:'february',february:'february',mar:'march',march:'march',apr:'april',april:'april',may:'may',jun:'june',june:'june',jul:'july',july:'july',aug:'august',august:'august',sep:'september',sept:'september',september:'september',oct:'october',october:'october',nov:'november',november:'november',dec:'december',december:'december'};
const MONTH_RE = Object.keys(MONTH).sort((a,b)=>b.length-a.length).join('|');
const COUNTRY = { putin:'russia', zelensky:'ukraine', xi:'china', macron:'france' };
const FILLER = new Set('what are is the of on by to for a an in and or if will would could being be polymarket odds probability chance chances market markets yes no price trading outcome outcomes'.split(' '));
const WEAK = new Set('out president before after during removed leave leaves office win wins lose loses happen happens perform by'.split(' '));

function isPolymarketOddsQuestion(q){return /\bpolymarket\b/i.test(q)&&/\b(odds|probability|chance|chances|price|market|yes|no)\b/i.test(q)}
function slugify(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function normalize(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function textOf(m){return normalize(m?.question||m?.title||m?.slug||'')}
function monthDay(q){const m=String(q||'').toLowerCase().match(new RegExp('\\b('+MONTH_RE+')\\b\\s*([1-3]?\\d)(?:st|nd|rd|th)?'));return m?{month:MONTH[m[1]]||m[1],short:(MONTH[m[1]]||m[1]).slice(0,3),day:String(Number(m[2]))}:null}
function keyTerms(q){const s=normalize(q);const date=monthDay(q);const terms=[];for(const w of s.split(/\s+/)){if(!w||FILLER.has(w))continue;if(MONTH[w]){terms.push(MONTH[w].slice(0,3));continue}if(/^\d+$/.test(w)){if(date&&w===date.day)terms.push(w);continue}terms.push(w)}return [...new Set(terms)]}
function subjectTerms(q){const terms=keyTerms(q).filter(w=>!WEAK.has(w)&&!FILLER.has(w)&&!MONTH[w]&&!/^\d+$/.test(w));return terms.slice(0,4)}
function hasSubject(marketText, subjects){return !subjects.length||subjects.some(s=>marketText.includes(s))}
function dateMatches(marketText,d){return !d||(marketText.includes(d.short)&&marketText.includes(d.day))}
function decode(v){if(Array.isArray(v))return v;if(typeof v!=='string')return[];try{const p=JSON.parse(v);return Array.isArray(p)?p:[]}catch{return[]}}
function outcomes(m){const names=decode(m.outcomes||m.outcomeNames),prices=decode(m.outcomePrices).map(Number);return names.map((n,i)=>({name:String(n||'').trim(),price:Number.isFinite(prices[i])?prices[i]:null}))}
function pickOutcome(m,want='Yes'){const outs=outcomes(m),w=String(want||'Yes').toLowerCase();return outs.find(o=>o.name.toLowerCase()===w)||outs.find(o=>o.name.toLowerCase().includes(w))||outs.find(o=>o.name.toLowerCase()==='yes')||outs[0]||{name:want,price:null}}
function fmt(p){if(p==null||!Number.isFinite(Number(p)))return'?';const pct=Number(p)*100;if(pct===0)return'<0.1%';return pct>0&&pct<1?pct.toFixed(2)+'%':pct.toFixed(1)+'%'}
async function j(url){try{const r=await fetch(url,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(10000)});return r.ok?await r.json():null}catch{return null}}
function marketsFrom(data){if(!data)return[];const roots=Array.isArray(data)?data:Array.isArray(data.data)?data.data:Array.isArray(data.events)?data.events:[data];const out=[];for(const r of roots){if(!r)continue;if(Array.isArray(r.markets))out.push(...r.markets);else if(r.outcomePrices&&(r.question||r.title))out.push(r)}return out.filter(m=>m&&(m.question||m.title)&&m.outcomePrices)}
async function groq(prompt,fb){const key=process.env.GROQ_API_KEY;if(!key)return fb;try{const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},signal:AbortSignal.timeout(9000),body:JSON.stringify({model:'llama-3.1-8b-instant',temperature:0,max_tokens:300,messages:[{role:'user',content:prompt}]})});if(!r.ok)return fb;const raw=((await r.json()).choices?.[0]?.message?.content||'').replace(/```json|```/g,'').trim();const m=raw.match(/\{[\s\S]*\}/);return JSON.parse(m?m[0]:raw)}catch{return fb}}
function urlSlug(q){const m=String(q||'').match(/polymarket\.com\/event\/([^\s?#]+)/i);return m?m[1].replace(/#.*$/,''):null}
function deterministicSlugs(q,parsed){const out=[];const u=urlSlug(q);if(u)out.push(u);const d=monthDay(q);const subjects=(parsed.subjects?.length?parsed.subjects:subjectTerms(q)).map(slugify).filter(Boolean);const subj=subjects[0];if(!d||!subj)return[...new Set(out)];const s=String(q).toLowerCase();const country=(s.match(/president\s+of\s+([a-z]+)/)||[])[1]||COUNTRY[subj]||'';const suffix=`${d.month}-${d.day}`;if(/\bout\b/.test(s)){if(/president/.test(s)||country){if(country)out.push(`${subj}-out-as-president-of-${slugify(country)}-by-${suffix}`);out.push(`${subj}-out-as-president-by-${suffix}`)}out.push(`${subj}-out-by-${suffix}`)}out.push(`${subjects.join('-')}-by-${suffix}`);return[...new Set(out)]}
async function parse(q){const terms=keyTerms(q),subjects=subjectTerms(q),d=monthDay(q);const fallback={searchQueries:[terms.join(' '),subjects.join(' ')].filter(Boolean),subjects,dateTerms:d?[d.short,d.day]:[],outcome:'Yes',slugCandidates:[]};const p=await groq('Parse this Polymarket odds question into JSON only: {"searchQueries":[queries],"subjects":[main entity/topic terms],"dateTerms":[month/day terms],"outcome":"Yes/No/exact outcome","slugCandidates":[possible event slugs]}. Keep only meaningful terms. Question: '+q,fallback);p.searchQueries=Array.isArray(p.searchQueries)&&p.searchQueries.length?p.searchQueries:fallback.searchQueries;p.subjects=Array.isArray(p.subjects)&&p.subjects.length?p.subjects.map(x=>String(x).toLowerCase()):fallback.subjects;p.dateTerms=Array.isArray(p.dateTerms)?[...new Set([...p.dateTerms.map(x=>String(x).toLowerCase().slice(0,3)),...fallback.dateTerms])]:fallback.dateTerms;p.outcome=p.outcome||'Yes';p.slugCandidates=[...new Set([...deterministicSlugs(q,p),...(Array.isArray(p.slugCandidates)?p.slugCandidates:[])].filter(Boolean))];return p}
async function exact(slug){const page='https://polymarket.com/event/'+slug;for(const u of[`https://gamma-api.polymarket.com/events/slug/${encodeURIComponent(slug)}`,`https://gamma-api.polymarket.com/events?slug=${encodeURIComponent(slug)}`,`https://gamma-api.polymarket.com/markets?slug=${encodeURIComponent(slug)}`]){const ms=marketsFrom(await j(u));if(ms.length)return{market:ms[0],url:page}}return null}
async function search(qs){const by=new Map();for(const q of[...new Set(qs.filter(Boolean))]){for(const u of['https://gamma-api.polymarket.com/markets?active=true&closed=false&limit=50&search='+encodeURIComponent(q),'https://gamma-api.polymarket.com/markets?limit=50&search='+encodeURIComponent(q)]){for(const m of marketsFrom(await j(u)))by.set(m.id||m.slug||m.question,m)}}return[...by.values()]}
function overlapScore(q,m){const mt=textOf(m),terms=keyTerms(q),subs=subjectTerms(q),d=monthDay(q);if(!hasSubject(mt,subs))return-999;if(d&&!dateMatches(mt,d))return-999;let score=0;for(const t of terms){if(mt.includes(t))score+=WEAK.has(t)?1:3}if(d)score+=8;if(subs.length)score+=10;return score}
async function aiPick(q,ms){if(ms.length<=1)return{index:ms.length?0:-1,outcome:'Yes'};const list=ms.slice(0,12).map((m,i)=>`${i}: ${m.question||m.title||m.slug}`).join('\n');return await groq('Pick exact Polymarket market. Return {"index":number,"outcome":"Yes/No/exact outcome"}; index -1 if none match subject/topic/date. Question: '+q+'\nMarkets:\n'+list,{index:0,outcome:'Yes'})}
function ans(m,outcome,urlOverride){const title=m.question||m.title||m.slug||'Selected market';const o=pickOutcome(m,outcome);const slug=m.slug||m.market_slug||'';const url=urlOverride||(slug?'https://polymarket.com/event/'+slug:'https://polymarket.com');return{ok:true,kind:'polymarket',answer:`${o.name||'Outcome'} is trading at ${fmt(o.price)} on Polymarket for: ${title}`,sources:[{domain:'polymarket',title:title.slice(0,90),url}],headlines:[]}}
async function answerPolymarketOddsQuestion(q){const p=await parse(q);for(const slug of p.slugCandidates){const ex=await exact(slug);if(ex?.market)return ans(ex.market,p.outcome,ex.url)}let candidates=(await search(p.searchQueries)).map(m=>({m,score:overlapScore(q,m)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).map(x=>x.m);if(!candidates.length)return{ok:false,kind:'polymarket',answer:'I could not find a Polymarket market that matches the subject/topic/date in your question.',sources:[],headlines:[]};const pick=await aiPick(q,candidates);if(Number(pick.index)<0||Number(pick.index)>=Math.min(12,candidates.length))return{ok:false,kind:'polymarket',answer:'I found Polymarket results, but none clearly matched your question.',sources:[],headlines:[]};return ans(candidates[Number(pick.index)],pick.outcome||p.outcome)}
module.exports={isPolymarketOddsQuestion,answerPolymarketOddsQuestion};